fix format

diff --git a/sync_diff_inspector/tests/_utils/check_contains_count b/sync_diff_inspector/tests/_utils/check_contains_count
--- a/sync_diff_inspector/tests/_utils/check_contains_count
+++ b/sync_diff_inspector/tests/_utils/check_contains_count
@@ -10,9 +10,9 @@ OUT_DIR=/tmp/tidb_tools_test
 count=$(grep -F "$1" "$2" | wc -l)
 
 if [ "$count" -ne "$3" ]; then
-    echo "TEST FAILED: '$2' DOES NOT CONTAIN '$1' $3 times"
-    echo "____________________________________"
-    cat "$2"
-    echo "^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^"
-    exit 1
+	echo "TEST FAILED: '$2' DOES NOT CONTAIN '$1' $3 times"
+	echo "____________________________________"
+	cat "$2"
+	echo "^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^"
+	exit 1
 fi
diff --git a/sync_diff_inspector/tests/_utils/check_not_contains b/sync_diff_inspector/tests/_utils/check_not_contains
--- a/sync_diff_inspector/tests/_utils/check_not_contains
+++ b/sync_diff_inspector/tests/_utils/check_not_contains
@@ -7,9 +7,9 @@ set -eu
 OUT_DIR=/tmp/tidb_binlog_test
 
 if grep -Fq "$1" "$2"; then
-    echo "TEST FAILED: '$2' CONTAIN '$1'"
-    echo "____________________________________"
-    cat "$2"
-    echo "^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^"
-    exit 1
+	echo "TEST FAILED: '$2' CONTAIN '$1'"
+	echo "____________________________________"
+	cat "$2"
+	echo "^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^"
+	exit 1
 fi
