Merge branch 'master' into tcp_branch
# Conflicts:
#	cdc/sink/sink.go

diff --git a/tests/_utils/check_sync_diff b/tests/_utils/check_sync_diff
--- a/tests/_utils/check_sync_diff
+++ b/tests/_utils/check_sync_diff
@@ -6,34 +6,40 @@
 workdir=$1
 conf=$2
 if [ $# -ge 3 ]; then
-    check_time=$3
+	check_time=$3
 else
-    check_time=30
+	check_time=30
 fi
 binary=sync_diff_inspector
 
 PWD=$(pwd)
 LOG=$workdir/sync_diff_inspector.log
+OUTPUT_DIR=/tmp/ticdc_dm_test/output/
+
+mkdir -p /tmp/ticdc_dm_test
 
 cd $workdir
 i=0
-while [ $i -lt $check_time ]
-do
-    $binary --config=$conf >> $LOG 2>&1
-    ret=$?
-    if [ "$ret" == 0 ]; then
-        echo "check diff successfully"
-        break
-    fi
-    ((i++))
-    echo "check diff failed $i-th time, retry later"
-    sleep 2
+while [ $i -lt $check_time ]; do
+	rm -rf $OUTPUT_DIR
+	$binary --config=$conf >>$LOG 2>&1
+	ret=$?
+	if [ "$ret" == 0 ]; then
+		echo "check diff successfully"
+		break
+	fi
+	((i++))
+	echo "check diff failed $i-th time, retry later"
+	sleep 2
 done
 
 if [ $i -ge $check_time ]; then
-    echo "check diff failed at last"
-    # show \n and other blanks
-    printf "$(cat $LOG)\n"
-    exit 1
+	echo "check diff failed at last"
+	# show \n and other blanks
+	cat $LOG
+	printf "\n"
+	cat $OUTPUT_DIR/sync_diff.log
+	printf "\n"
+	exit 1
 fi
 cd $PWD
