lint: add shfmt to format sh scripts (#2882)

diff --git a/tests/_utils/ensure b/tests/_utils/ensure
--- a/tests/_utils/ensure
+++ b/tests/_utils/ensure
@@ -4,16 +4,16 @@
 
 total=$1
 shift
-for ((i = 1 ; i <= $total ; i++)); do
-    # run the command
-    echo $*
-    bash -c "$*"
-    if [ $? == 0 ]; then
-        echo "run task successfully"
-        exit 0
-    fi
-    echo "run task failed $i-th time, retry later"
-    sleep 2
+for ((i = 1; i <= $total; i++)); do
+	# run the command
+	echo $*
+	bash -c "$*"
+	if [ $? == 0 ]; then
+		echo "run task successfully"
+		exit 0
+	fi
+	echo "run task failed $i-th time, retry later"
+	sleep 2
 done
 
 echo "run task failed"
diff --git a/tests/_utils/start_tls_tidb_cluster b/tests/_utils/start_tls_tidb_cluster
--- a/tests/_utils/start_tls_tidb_cluster
+++ b/tests/_utils/start_tls_tidb_cluster
@@ -11,28 +11,29 @@ TLS_DIR=
 retry_times=3
 
 while [[ ${1} ]]; do
-    case "${1}" in
-        --workdir)
-            OUT_DIR=${2}
-            shift
-            ;;
-        --tlsdir)
-            TLS_DIR=${2}
-            shift
-            ;;
-        --retry)
-            retry_times=${2}
-            shift
-            ;;
-        *)
-            echo "Unknown parameter: ${1}" >&2
-            exit 1
-    esac
+	case "${1}" in
+	--workdir)
+		OUT_DIR=${2}
+		shift
+		;;
+	--tlsdir)
+		TLS_DIR=${2}
+		shift
+		;;
+	--retry)
+		retry_times=${2}
+		shift
+		;;
+	*)
+		echo "Unknown parameter: ${1}" >&2
+		exit 1
+		;;
+	esac
 
-    if ! shift; then
-        echo 'Missing parameter argument.' >&2
-        exit 1
-    fi
+	if ! shift; then
+		echo 'Missing parameter argument.' >&2
+		exit 1
+	fi
 done
 
 CUR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
@@ -40,15 +41,14 @@ source $CUR/../_utils/test_prepare
 
 set +e
 i=1
-while [ $i -le $retry_times ]
-do
-    echo "The ${i} times to try to start tls tidb cluster..."
+while [ $i -le $retry_times ]; do
+	echo "The ${i} times to try to start tls tidb cluster..."
 
-    start_tls_tidb_cluster_impl --workdir ${OUT_DIR} --tlsdir ${TLS_DIR}
+	start_tls_tidb_cluster_impl --workdir ${OUT_DIR} --tlsdir ${TLS_DIR}
 
-    if [ $? -eq 0 ]; then
-        break
-    fi
-    let i++
-    echo "start tls tidb cluster failed"
+	if [ $? -eq 0 ]; then
+		break
+	fi
+	let i++
+	echo "start tls tidb cluster failed"
 done
