This is an automated cherry-pick of #2798
Signed-off-by: ti-chi-bot <ti-community-prow-bot@tidb.io>

diff --git a/tests/_utils/run_cdc_server b/tests/_utils/run_cdc_server
--- a/tests/_utils/run_cdc_server
+++ b/tests/_utils/run_cdc_server
@@ -25,6 +25,7 @@ config_path=
 data_dir=
 
 while [[ ${1} ]]; do
+<<<<<<< HEAD
     case "${1}" in
         --workdir)
             workdir=${2}
@@ -87,6 +88,74 @@ done
 
 if [ -z "$data_dir" ]; then
     data_dir=${workdir}/cdc_data${logsuffix}
+=======
+	case "${1}" in
+	--workdir)
+		workdir=${2}
+		shift
+		;;
+	--tlsdir)
+		tls_dir=${2}
+		tls="--ca ${2}/ca.pem --cert ${2}/server.pem --key ${2}/server-key.pem"
+		shift
+		;;
+	--cert-allowed-cn)
+		certcn_name=${2}
+		certcn="--cert-allowed-cn ${2}"
+		shift
+		;;
+	--binary)
+		binary=${2}
+		shift
+		;;
+	--logsuffix)
+		logsuffix=${2}
+		shift
+		;;
+	--addr)
+		addr_url=${2}
+		addr="--addr ${2}"
+		shift
+		;;
+	--pd)
+		pd_addr="--pd ${2}"
+		shift
+		;;
+	--loglevel)
+		log_level=${2}
+		shift
+		;;
+	--restart)
+		restart=${2}
+		shift
+		;;
+	--failpoint)
+		failpoint=${2}
+		shift
+		;;
+	--config)
+		config_path="--config ${2}"
+		shift
+		;;
+	--data-dir)
+		data_dir=${2}
+		shift
+		;;
+	*)
+		echo "Unknown parameter: ${1}" >&2
+		exit 1
+		;;
+	esac
+
+	if ! shift; then
+		echo 'Missing parameter argument.' >&2
+		exit 1
+	fi
+done
+
+if [ -z "$data_dir" ]; then
+	data_dir=${workdir}/cdc_data${logsuffix}
+>>>>>>> 257041655 (lint: add shfmt to format sh scripts (#2798))
 fi
 
 echo "[$(date)] <<<<<< START cdc server in $TEST_NAME case >>>>>>"
@@ -96,6 +165,7 @@ pid=$(ps -C run_cdc_server -o pid=|tr -d '[:space:]')
 # GRPC_GO_LOG_VERBOSITY_LEVEL=99 GRPC_GO_LOG_SEVERITY_LEVEL=debug \
 
 if [[ "$restart" == "true" ]]; then
+<<<<<<< HEAD
   while true; do
       GO_FAILPOINTS=$failpoint $binary -test.coverprofile="$OUT_DIR/cov.$TEST_NAME.$pid.out" server \
         --log-file $workdir/cdc$logsuffix.log \
@@ -126,5 +196,64 @@ else
 fi
 
 cd $pwd
+=======
+	while true; do
+		GO_FAILPOINTS=$failpoint $binary -test.coverprofile="$OUT_DIR/cov.$TEST_NAME.$pid.out" server \
+			--log-file $workdir/cdc$logsuffix.log \
+			--log-level $log_level \
+			--sorter-num-workerpool-goroutine 4 \
+			--data-dir "$data_dir" \
+			$config_path \
+			$tls \
+			$certcn \
+			$addr \
+			$pd_addr &>>$workdir/stdout$logsuffix.log
+		if [ $? -eq 143 ]; then
+			break
+		fi
+		sleep 1
+	done &
+else
+	GO_FAILPOINTS=$failpoint $binary -test.coverprofile="$OUT_DIR/cov.$TEST_NAME.$pid.out" server \
+		--log-file $workdir/cdc$logsuffix.log \
+		--log-level $log_level \
+		--sorter-num-workerpool-goroutine 4 \
+		--data-dir "$data_dir" \
+		$config_path \
+		$tls \
+		$certcn \
+		$addr \
+		$pd_addr &>>$workdir/stdout$log_suffix.log &
+fi
+
+# Make sure cdc is ready to serve
+
+# Because curl may encounter errors,
+# it is acceptable and will retry, so you cannot quit.
+set +e
+
+get_info_fail_msg="failed to get info:"
+etcd_info_msg="etcd info"
+# If tls is set, then we need to pass the certificate and use https.
+# Note that the certificate name may be specified.
+if [ -z "$tls_dir" ]; then
+	curl_status_cmd="curl -vsL http://$addr_url/debug/info"
+else
+	curl_status_cmd="curl --cacert $tls_dir/ca.pem --cert $tls_dir/$certcn_name.pem --key $tls_dir/$certcn_name-key.pem -vsL https://$addr_url/debug/info"
+fi
+
+for ((i = 0; i <= 50; i++)); do
+	res=$($curl_status_cmd)
+	# Make sure we get the capture info(etcd_info_msg) and that there are no errors(get_info_fail_msg).
+	if (! echo "$res" | grep -q "$get_info_fail_msg") && (echo "$res" | grep -q "$etcd_info_msg"); then
+		break
+	fi
+	if [ "$i" -eq 50 ]; then
+		echo 'Failed to start TiCDC'
+		exit 1
+	fi
+	sleep 3
+done
+>>>>>>> 257041655 (lint: add shfmt to format sh scripts (#2798))
 
 
diff --git a/tests/_utils/start_tls_tidb_cluster_impl b/tests/_utils/start_tls_tidb_cluster_impl
--- a/tests/_utils/start_tls_tidb_cluster_impl
+++ b/tests/_utils/start_tls_tidb_cluster_impl
@@ -9,24 +9,25 @@ OUT_DIR=
 TLS_DIR=
 
 while [[ ${1} ]]; do
-    case "${1}" in
-        --workdir)
-            OUT_DIR=${2}
-            shift
-            ;;
-        --tlsdir)
-            TLS_DIR=${2}
-            shift
-            ;;
-        *)
-            echo "Unknown parameter: ${1}" >&2
-            exit 1
-    esac
+	case "${1}" in
+	--workdir)
+		OUT_DIR=${2}
+		shift
+		;;
+	--tlsdir)
+		TLS_DIR=${2}
+		shift
+		;;
+	*)
+		echo "Unknown parameter: ${1}" >&2
+		exit 1
+		;;
+	esac
 
-    if ! shift; then
-        echo 'Missing parameter argument.' >&2
-        exit 1
-    fi
+	if ! shift; then
+		echo 'Missing parameter argument.' >&2
+		exit 1
+	fi
 done
 
 CUR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
@@ -34,7 +35,7 @@ source $CUR/../_utils/test_prepare
 
 cd $OUT_DIR && echo "start tidb cluster in $OUT_DIR"
 
-cat - > "$OUT_DIR/pd-config-tls.toml" <<EOF
+cat - >"$OUT_DIR/pd-config-tls.toml" <<EOF
 [replication]
 # The number of replicas for each region.
 max-replicas = 1
@@ -46,29 +47,29 @@ EOF
 
 echo "Starting TLS PD..."
 pd-server \
-    --client-urls https://${TLS_PD_HOST}:${TLS_PD_PORT}\
-    --peer-urls https://${TLS_PD_HOST}:${TLS_PD_PEER_PORT}\
-    --config "$OUT_DIR/pd-config-tls.toml" \
-    --log-file "$OUT_DIR/pd_tls.log" \
-    --data-dir "$OUT_DIR/pd_tls" &
+	--client-urls https://${TLS_PD_HOST}:${TLS_PD_PORT} \
+	--peer-urls https://${TLS_PD_HOST}:${TLS_PD_PEER_PORT} \
+	--config "$OUT_DIR/pd-config-tls.toml" \
+	--log-file "$OUT_DIR/pd_tls.log" \
+	--data-dir "$OUT_DIR/pd_tls" &
 
 # wait until PD is online...
 while ! curl --cacert $TLS_DIR/ca.pem \
-        --cert $TLS_DIR/client.pem \
-        --key $TLS_DIR/client-key.pem \
-        -o /dev/null -sf https://${TLS_PD_HOST}:${TLS_PD_PORT}/pd/api/v1/version; do
-    sleep 1
+	--cert $TLS_DIR/client.pem \
+	--key $TLS_DIR/client-key.pem \
+	-o /dev/null -sf https://${TLS_PD_HOST}:${TLS_PD_PORT}/pd/api/v1/version; do
+	sleep 1
 done
 
 while [ -z "$(curl --cacert $TLS_DIR/ca.pem \
-        --cert $TLS_DIR/client.pem \
-        --key $TLS_DIR/client-key.pem \
-        https://${TLS_PD_HOST}:${TLS_PD_PORT}/pd/health 2> /dev/null | grep 'health' | grep 'true')" ]; do
-    sleep 1
+	--cert $TLS_DIR/client.pem \
+	--key $TLS_DIR/client-key.pem \
+	https://${TLS_PD_HOST}:${TLS_PD_PORT}/pd/health 2>/dev/null | grep 'health' | grep 'true')" ]; do
+	sleep 1
 done
 
 # Tries to limit the max number of open files under the system limit
-cat - > "$OUT_DIR/tikv-config-tls.toml" <<EOF
+cat - >"$OUT_DIR/tikv-config-tls.toml" <<EOF
 [storage]
 # Disable creating a large temp file.
 reserve-space = "0MB"
@@ -86,7 +87,7 @@ key-path = "$TLS_DIR/server-key.pem"
 EOF
 
 # tidb server config file
-cat - > "$OUT_DIR/tidb-config-tls.toml" <<EOF
+cat - >"$OUT_DIR/tidb-config-tls.toml" <<EOF
 split-table = true
 alter-primary-key = true
 new_collations_enabled_on_first_bootstrap = true
@@ -105,47 +106,54 @@ echo "Starting TLS TiKV..."
 # GRPC_VERBOSITY=debug \
 # GRPC_TRACE=server_channel,call_error,handshaker,tsi \
 tikv-server \
-    --pd ${TLS_PD_HOST}:${TLS_PD_PORT} \
-    -A ${TLS_TIKV_HOST}:${TLS_TIKV_PORT} \
-    --status-addr ${TLS_TIKV_HOST}:${TLS_TIKV_STATUS_PORT} \
-    --log-file "$OUT_DIR/tikv_tls.log" \
-    -C "$OUT_DIR/tikv-config-tls.toml" \
-    -s "$OUT_DIR/tikv_tls" &> $OUT_DIR/tikv_tls.stdout &
+	--pd ${TLS_PD_HOST}:${TLS_PD_PORT} \
+	-A ${TLS_TIKV_HOST}:${TLS_TIKV_PORT} \
+	--status-addr ${TLS_TIKV_HOST}:${TLS_TIKV_STATUS_PORT} \
+	--log-file "$OUT_DIR/tikv_tls.log" \
+	-C "$OUT_DIR/tikv-config-tls.toml" \
+	-s "$OUT_DIR/tikv_tls" &>$OUT_DIR/tikv_tls.stdout &
 
 sleep 2
 
 echo "Starting TLS TiDB..."
 tidb-server \
-    -P ${TLS_TIDB_PORT} \
-    -config "$OUT_DIR/tidb-config-tls.toml" \
-    --store tikv \
-    --path ${TLS_PD_HOST}:${TLS_PD_PORT} \
-    --status=${TLS_TIDB_STATUS} \
-    --log-file "$OUT_DIR/tidb_tls.log" &
+	-P ${TLS_TIDB_PORT} \
+	-config "$OUT_DIR/tidb-config-tls.toml" \
+	--store tikv \
+	--path ${TLS_PD_HOST}:${TLS_PD_PORT} \
+	--status=${TLS_TIDB_STATUS} \
+	--log-file "$OUT_DIR/tidb_tls.log" &
 
 echo "Verifying TLS TiDB is started..."
 i=0
 while ! mysql -uroot -h${TLS_TIDB_HOST} -P${TLS_TIDB_PORT} --default-character-set utf8mb4 -e 'select * from mysql.tidb;'; do
-    i=$((i + 1))
-    if [ "$i" -gt 60 ]; then
-        echo 'Failed to start upstream TiDB'
-        exit 2
-    fi
-    sleep 2
+	i=$((i + 1))
+	if [ "$i" -gt 60 ]; then
+		echo 'Failed to start upstream TiDB'
+		exit 2
+	fi
+	sleep 2
 done
 
 run_sql "update mysql.tidb set variable_value='60m' where variable_name='tikv_gc_life_time';" ${TLS_TIDB_HOST} ${TLS_TIDB_PORT} \
-    --ssl-ca=$TLS_DIR/ca.pem \
-    --ssl-cert=$TLS_DIR/server.pem \
-    --ssl-key=$TLS_DIR/server-key.pem
+	--ssl-ca=$TLS_DIR/ca.pem \
+	--ssl-cert=$TLS_DIR/server.pem \
+	--ssl-key=$TLS_DIR/server-key.pem
 
 echo "Starting CDC state checker..."
 cd $CUR/../../testing_utils/cdc_state_checker
 if [ ! -f ./cdc_state_checker ]; then
-  GO111MODULE=on go build
+	GO111MODULE=on go build
 fi
+<<<<<<< HEAD
 ./cdc_state_checker -pd ${TLS_PD_HOST}:${TLS_PD_PORT} \
     -ca $TLS_DIR/ca.pem \
     -cert $TLS_DIR/server.pem \
     -key $TLS_DIR/server-key.pem > $OUT_DIR/cdc_etcd_check.log &
+=======
+./cdc_state_checker -pd https://${TLS_PD_HOST}:${TLS_PD_PORT} \
+	-ca $TLS_DIR/ca.pem \
+	-cert $TLS_DIR/server.pem \
+	-key $TLS_DIR/server-key.pem >$OUT_DIR/cdc_etcd_check.log &
+>>>>>>> 257041655 (lint: add shfmt to format sh scripts (#2798))
 cd $OUT_DIR
