lint: add shfmt to format sh scripts (#2884)

diff --git a/tests/_utils/run_cdc_server b/tests/_utils/run_cdc_server
--- a/tests/_utils/run_cdc_server
+++ b/tests/_utils/run_cdc_server
@@ -25,106 +25,105 @@ config_path=
 data_dir=
 
 while [[ ${1} ]]; do
-    case "${1}" in
-        --workdir)
-            workdir=${2}
-            shift
-            ;;
-        --tlsdir)
-            tls="--ca ${2}/ca.pem --cert ${2}/server.pem --key ${2}/server-key.pem"
-            shift
-            ;;
-        --cert-allowed-cn)
-            certcn="--cert-allowed-cn ${2}"
-            shift
-            ;;
-        --binary)
-            binary=${2}
-            shift
-            ;;
-        --logsuffix)
-            logsuffix=${2}
-            shift
-            ;;
-        --addr)
-            addr="--addr ${2}"
-            shift
-            ;;
-        --pd)
-            pd_addr="--pd ${2}"
-            shift
-            ;;
-        --loglevel)
-            log_level=${2}
-            shift
-            ;;
-        --restart)
-            restart=${2}
-            shift
-            ;;
-        --failpoint)
-            failpoint=${2}
-            shift
-            ;;
-        --config)
-            config_path="--config ${2}"
-            shift
-            ;;
-        --data-dir)
-            data_dir=${2}
-            shift
-            ;;
-        *)
-            echo "Unknown parameter: ${1}" >&2
-            exit 1
-    esac
+	case "${1}" in
+	--workdir)
+		workdir=${2}
+		shift
+		;;
+	--tlsdir)
+		tls="--ca ${2}/ca.pem --cert ${2}/server.pem --key ${2}/server-key.pem"
+		shift
+		;;
+	--cert-allowed-cn)
+		certcn="--cert-allowed-cn ${2}"
+		shift
+		;;
+	--binary)
+		binary=${2}
+		shift
+		;;
+	--logsuffix)
+		logsuffix=${2}
+		shift
+		;;
+	--addr)
+		addr="--addr ${2}"
+		shift
+		;;
+	--pd)
+		pd_addr="--pd ${2}"
+		shift
+		;;
+	--loglevel)
+		log_level=${2}
+		shift
+		;;
+	--restart)
+		restart=${2}
+		shift
+		;;
+	--failpoint)
+		failpoint=${2}
+		shift
+		;;
+	--config)
+		config_path="--config ${2}"
+		shift
+		;;
+	--data-dir)
+		data_dir=${2}
+		shift
+		;;
+	*)
+		echo "Unknown parameter: ${1}" >&2
+		exit 1
+		;;
+	esac
 
-    if ! shift; then
-        echo 'Missing parameter argument.' >&2
-        exit 1
-    fi
+	if ! shift; then
+		echo 'Missing parameter argument.' >&2
+		exit 1
+	fi
 done
 
 if [ -z "$data_dir" ]; then
-    data_dir=${workdir}/cdc_data${logsuffix}
+	data_dir=${workdir}/cdc_data${logsuffix}
 fi
 
 echo "[$(date)] <<<<<< START cdc server in $TEST_NAME case >>>>>>"
 cd $workdir
-pid=$(ps -C run_cdc_server -o pid=|tr -d '[:space:]')
+pid=$(ps -C run_cdc_server -o pid= | tr -d '[:space:]')
 # Uncomment to turn on grpc versbose log.
 # GRPC_GO_LOG_VERBOSITY_LEVEL=99 GRPC_GO_LOG_SEVERITY_LEVEL=debug \
 
 if [[ "$restart" == "true" ]]; then
-  while true; do
-      GO_FAILPOINTS=$failpoint $binary -test.coverprofile="$OUT_DIR/cov.$TEST_NAME.$pid.out" server \
-        --log-file $workdir/cdc$logsuffix.log \
-        --log-level $log_level \
-        --sorter-num-workerpool-goroutine 4 \
-        --data-dir "$data_dir" \
-        $config_path \
-        $tls \
-        $certcn \
-        $addr \
-        $pd_addr &>> $workdir/stdout$logsuffix.log
-      if [ $? -eq 143 ]; then
-        break
-      fi
-      sleep 1
-  done &
+	while true; do
+		GO_FAILPOINTS=$failpoint $binary -test.coverprofile="$OUT_DIR/cov.$TEST_NAME.$pid.out" server \
+			--log-file $workdir/cdc$logsuffix.log \
+			--log-level $log_level \
+			--sorter-num-workerpool-goroutine 4 \
+			--data-dir "$data_dir" \
+			$config_path \
+			$tls \
+			$certcn \
+			$addr \
+			$pd_addr &>>$workdir/stdout$logsuffix.log
+		if [ $? -eq 143 ]; then
+			break
+		fi
+		sleep 1
+	done &
 else
-  GO_FAILPOINTS=$failpoint $binary -test.coverprofile="$OUT_DIR/cov.$TEST_NAME.$pid.out" server \
-    --log-file $workdir/cdc$logsuffix.log \
-    --log-level $log_level \
-    --sorter-num-workerpool-goroutine 4 \
-    --data-dir "$data_dir" \
-    $config_path \
-    $tls \
-    $certcn \
-    $addr \
-    $pd_addr &>> $workdir/stdout$log_suffix.log &
+	GO_FAILPOINTS=$failpoint $binary -test.coverprofile="$OUT_DIR/cov.$TEST_NAME.$pid.out" server \
+		--log-file $workdir/cdc$logsuffix.log \
+		--log-level $log_level \
+		--sorter-num-workerpool-goroutine 4 \
+		--data-dir "$data_dir" \
+		$config_path \
+		$tls \
+		$certcn \
+		$addr \
+		$pd_addr &>>$workdir/stdout$log_suffix.log &
 fi
 
 cd $pwd
-
-
