fix script fmt

diff --git a/engine/test/utils/create_job b/engine/test/utils/create_job
--- a/engine/test/utils/create_job
+++ b/engine/test/utils/create_job
@@ -27,21 +27,21 @@ job_id=""
 retry_time=15
 i=0
 while [ $i -lt $retry_time ]; do
-    output=$(curl -X POST -H "Content-Type: application/json" -d "$create_job_json" "http://127.0.0.1:10245/api/v1/jobs?tenant_id=${tenant_id}&project_id=${project_id})" | tee /dev/stderr)
-    code=$(echo $output | jq -r .code)
-    if [ -z "$code" ]; then
-        job_id=$(echo $output | jq -r .id)
-        break
-    else
-        ((i++))
-        echo -e "create job failed $i-th time, retry later, error: $output" >/dev/stderr
-        sleep 2
-    fi
+	output=$(curl -X POST -H "Content-Type: application/json" -d "$create_job_json" "http://127.0.0.1:10245/api/v1/jobs?tenant_id=${tenant_id}&project_id=${project_id})" | tee /dev/stderr)
+	code=$(echo $output | jq -r .code)
+	if [ "$code" == "null" ]; then
+		job_id=$(echo $output | jq -r .id)
+		break
+	else
+		((i++))
+		echo -e "create job failed $i-th time, retry later, error: $output" >/dev/stderr
+		sleep 2
+	fi
 done
 
 if [ $i -ge $retry_time ]; then
 	echo "create job failed at last"
-    exit 1
+	exit 1
 else
-    echo $job_id
+	echo $job_id
 fi
