use openapi

diff --git a/engine/test/utils/start_engine_cluster b/engine/test/utils/start_engine_cluster
--- a/engine/test/utils/start_engine_cluster
+++ b/engine/test/utils/start_engine_cluster
@@ -21,5 +21,15 @@ if [ $i -gt $retry_times ]; then
 	exit 1
 else
 	# TODO: add check logic to wait cluster ready
-	sleep 20
+	i=1
+	while [ $i -le 30 ]; do
+		echo "The ${i} times to check engine cluster..."
+		# check engine cluster
+		curl -X GET "http://127.0.0.1:10245/api/v1/leader" && break || sleep 1 
+	done
+
+	if [ $i -gt 30 ]; then
+		echo -e "\n\n[$(date)] <<<<<< fail to start engine cluster after $retry_times times >>>>>>"
+		exit 1
+	fi
 fi
