remove execution terminate

diff --git a/engine/test/utils/start_engine_cluster b/engine/test/utils/start_engine_cluster
--- a/engine/test/utils/start_engine_cluster
+++ b/engine/test/utils/start_engine_cluster
@@ -8,13 +8,16 @@ echo "start deploying engine cluster..."
 
 retry_times=3
 i=1
+set -e
 while [ $i -le $retry_times ]; do
 	echo "The ${i} times to try to start engine cluster..."
 	run_engine.sh deploy "$@" && break
 	((i++)) || true
 	run_engine.sh stop "$@" || true
-	echo "start engine cluster failed"
+	echo "start engine cluster failed, retry later..."
+    sleep 3
 done
+set +e
 
 if [ $i -gt $retry_times ]; then
 	echo -e "\n\n[$(date)] <<<<<< fail to start engine cluster after $retry_times times >>>>>>"
