check all components

diff --git a/engine/test/utils/start_engine_cluster b/engine/test/utils/start_engine_cluster
--- a/engine/test/utils/start_engine_cluster
+++ b/engine/test/utils/start_engine_cluster
@@ -4,6 +4,20 @@ if [ $# -eq 0 ]; then
 	echo "<<<<<< can not deploy engine cluster using empty config >>>>>>"
 	exit 1
 fi
+
+function check_cluster() {
+	i=1
+	while [ $i -le 30 ]; do
+		echo -e "\nThe ${i} times to check ${1}..."
+		curl -X GET "http://127.0.0.1:10245/api/v1/${1}" && break || sleep 1 
+	done
+
+	if [ $i -gt 30 ]; then
+		echo -e "\n\n[$(date)] <<<<<< fail to start engine cluster after $retry_times times >>>>>>"
+		exit 1
+	fi
+}
+
 echo "start deploying engine cluster..."
 
 retry_times=3
@@ -20,16 +34,7 @@ if [ $i -gt $retry_times ]; then
 	echo -e "\n\n[$(date)] <<<<<< fail to start engine cluster after $retry_times times >>>>>>"
 	exit 1
 else
-	# TODO: add check logic to wait cluster ready
-	i=1
-	while [ $i -le 30 ]; do
-		echo "The ${i} times to check engine cluster..."
-		# check engine cluster
-		curl -X GET "http://127.0.0.1:10245/api/v1/leader" && break || sleep 1 
-	done
-
-	if [ $i -gt 30 ]; then
-		echo -e "\n\n[$(date)] <<<<<< fail to start engine cluster after $retry_times times >>>>>>"
-		exit 1
-	fi
+	check_cluster leader
+	check_cluster masters
+	check_cluster executors
 fi
