add pulsar oauth2 integration tests

diff --git a/tests/integration_tests/_utils/run_pulsar_cluster b/tests/integration_tests/_utils/run_pulsar_cluster
--- a/tests/integration_tests/_utils/run_pulsar_cluster
+++ b/tests/integration_tests/_utils/run_pulsar_cluster
@@ -54,6 +54,16 @@ mtls_client_conf=$(
 	EOF
 )
 
+oauth_client_conf=$(
+	cat <<-EOF
+
+    webServiceUrl=http://localhost:8080/
+    brokerServiceUrl=pulsar://localhost:6650/
+    authPlugin=org.apache.pulsar.client.impl.auth.oauth2.AuthenticationOAuth2
+    authParams={"privateKey":"${workdir}/credential.json","audience":"cdc-api-uri","issuerUrl":"http://localhost:9096"}
+	EOF
+)
+
 oauth_conf=$(
 	cat <<-EOF
 
@@ -61,9 +71,22 @@ oauth_conf=$(
 		authenticationProviders=org.apache.pulsar.broker.authentication.AuthenticationProviderToken
 
 		brokerClientAuthenticationPlugin=org.apache.pulsar.client.impl.auth.oauth2.AuthenticationOAuth2
-		brokerClientAuthenticationParameters={"privateKey":"file://${workdir}/privateKey","audience":"https://dev-kt-aa9ne.us.auth0.com/api/v2/","issuerUrl":"https://dev-kt-aa9ne.us.auth0.com"}
-		tokenSecretKey=file://${workdir}/secret.key
+		brokerClientAuthenticationParameters={"privateKey":"file://${workdir}/credential.json","audience":"cdc-api-uri","issuerUrl":"http://localhost:9096"}
+		tokenSecretKey=file://${workdir}/token-secret.key
 	EOF
+)
+
+credential_json=$(
+  	cat <<-EOF
+
+  		{
+        "client_id":"1234",
+        "client_secret":"e0KVlA2EiBfjoN13olyZd2kv1KL",
+        "audience":"cdc-api-uri",
+        "grant_type":"client_credentials",
+        "type": "client_credentials"
+      }
+    EOF
 )
 
 cert_server_conf=$(
@@ -107,7 +130,10 @@ function gen_mtls_config() {
 }
 
 function gen_oauth_config() {
+    echo "$credential_json" >${workdir}/credential.json
+    echo "SJhX36_KapYSybBtJq35lxX_Brr4LRURSkm7QmXJGmy8pUFW9EIOcVQPsykz9-jj" >${workdir}/token-secret.key
 	echo "$oauth_conf" >>${workdir}/pulsar_standalone.conf
+	echo "$oauth_client_conf" >${pulsar_dir}/conf/client.conf
 }
 
 echo "$normal_client_conf" >${pulsar_dir}/conf/client.conf
@@ -118,6 +144,18 @@ if [ "$cluster_type" == "mtls" ]; then
 	pulsar_port=6651
 	gen_mtls_config
 elif [ "$cluster_type" == "oauth" ]; then
+    oauth2-server >>$workdir/oauth_server.log 2>&1 &
+    echo "Waiting for oauth2 server to be ready..."
+    i=0
+    while ! nc -z localhost "9096"; do
+    	i=$((i + 1))
+    	if [ "$i" -gt 10 ]; then
+    		cat $workdir/oauth_server.log
+    		echo 'Failed to start oauth2 server'
+    		exit 1
+    	fi
+    	sleep 2
+    done
 	gen_oauth_config
 else
 	echo "no cluster type specified, using default configuration."
