modify code style

diff --git a/tests/integration_tests/_utils/start_tidb_cluster b/tests/integration_tests/_utils/start_tidb_cluster
--- a/tests/integration_tests/_utils/start_tidb_cluster
+++ b/tests/integration_tests/_utils/start_tidb_cluster
@@ -62,30 +62,30 @@ source $CUR/../_utils/test_prepare
 set +e
 i=1
 while [ $i -le $retry_times ]; do
-    echo "The ${i} times to try to start tidb cluster..."
+	echo "The ${i} times to try to start tidb cluster..."
 
-    # construct args
-    args="--workdir ${OUT_DIR} --multiple-upstream-pd ${multiple_upstream_pd}"
+	# construct args
+	args="--workdir ${OUT_DIR} --multiple-upstream-pd ${multiple_upstream_pd}"
 
-    if [[ -n "$tidb_config" ]]; then
-        args+=" --tidb-config ${tidb_config}"
-    elif [[ -n "$pd_config" ]]; then
-        args+=" --pd-config ${pd_config}"
-    elif [[ -n "$tikv_config" ]]; then
-        args+=" --tikv-config ${tikv_config}"
-    fi
+	if [[ -n "$tidb_config" ]]; then
+		args+=" --tidb-config ${tidb_config}"
+	elif [[ -n "$pd_config" ]]; then
+		args+=" --pd-config ${pd_config}"
+	elif [[ -n "$tikv_config" ]]; then
+		args+=" --tikv-config ${tikv_config}"
+	fi
 
-    if [[ -n "$down_db_tls_dir" ]]; then
-        args+=" --down-db-tls-dir ${down_db_tls_dir}"
-    fi
+	if [[ -n "$down_db_tls_dir" ]]; then
+		args+=" --down-db-tls-dir ${down_db_tls_dir}"
+	fi
 
-    # execute start_tidb_cluster_impl
-    start_tidb_cluster_impl ${args}
+	# execute start_tidb_cluster_impl
+	start_tidb_cluster_impl ${args}
 
-    if [ $? -eq 0 ]; then
-        break
-    fi
+	if [ $? -eq 0 ]; then
+		break
+	fi
 
-    let i++
-    echo "start tidb cluster failed"
+	let i++
+	echo "start tidb cluster failed"
 done
